### ISSUE TITLE
cmake-config files point to paths used during building

### ISSUE THREAD

**Issue by v01d** [ethz-asl/libnabo#31]
The libnaboTargets.cmake file, generated and installed into ros system directory after building, containts the following line:

IMPORTED_LOCATION_RELEASE "/home/v01d/pkgs/ros/arch-ros-stacks/indigo/libnabo/src/build/libnabo.so.1.0.6"

Which you can see references the build directory and not the real installed location. This makes libpointmatcher compilation fail.

**Comment by HannesSommer** [comment]
Thanks for the rising this issue. 
This is bug in libnabo's cmake code. 
It is apparently wrong to install files exported via http://www.cmake.org/cmake/help/v3.0/command/export.html, because their content will be build tree dependent.

I don't know exactly what the purpose was the installation of this file was introduced for. 

In PR #32 I've suggested removing all related code. It would be great if you, @v01d, could test the PR on your system, and post if it works for you.

**Comment by HannesSommer** [comment]
This is probably solved as PR #32 is merged into master.
